# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f61ee300a00a275d7fdefd3bc936f948fb79d667c811175c76e204f84ccd6b8ef937e8eebf8cffbc7283c6cd9e67829bedfffdbd26c6b9540437de29d6d8007

test:
  secret_key_base: a5830d518274bc8e6388401dc227289c009f0f8fac2a486f448cfdfcf6695644066cbca004b359a43a2a7ac016bdcc9f92807e13b0d1c028119672904d31c022

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
